version: '3.7'

services:

  frontend:
    image: frontend
    ports:
      - 5000:5000
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/

  backend:
    image: backend
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis
  
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
      