version: '3.7'

services:

 frontend:
  image: frontend
  ports:
   - 5000:5000
  container_name: frontend

 backend:
  image: backend
  ports:
   - 8080:8080
  container_name: backend
  environment:
   - REDIS_HOST=redis

 redis:
  image: redis
  container_name: redis
